displayName: MaxMind GeoIP2

summary: 'Traefik plugin that registers a custom middleware for getting data from MaxMind GeoIP databases and pass it downstream via HTTP request headers.'

type: middleware

import: github.com/GiGInnovationLabs/traefikgeoip2

testData:
  dbPath: 'GeoLite2-Country.mmdb'
